package uk.ac.gla.dcs.bigdata.providedstructures;

import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Serializable;
import java.util.List;

public class DocumentRanking implements Serializable{

	private static final long serialVersionUID = 2675653150567946299L;
	
	Query query;
	List<RankedResult> results;
	
	public DocumentRanking() {}
	
	public DocumentRanking(Query query, List<RankedResult> results) {
		super();
		this.query = query;
		this.results = results;
	}
	
	public Query getQuery() {
		return query;
	}
	public void setQuery(Query query) {
		this.query = query;
	}
	public List<RankedResult> getResults() {
		return results;
	}
	public void setResults(List<RankedResult> results) {
		this.results = results;
	}
	
	public String toString() {
		
		// The reason for using StringBuilder instead of string splicing (using +) is that it's better in terms of performance, especially when splicing strings in a loop.
		StringBuilder builder = new StringBuilder();
		// Adds the raw query string to the builder.
		builder.append(query.getOriginalQuery());
		builder.append("\n");
		
		int counter = 1;  // Initialise a counter to number the results.
		for (RankedResult result : results) {
			builder.append("  ");
			builder.append(counter);
			builder.append(":");
			builder.append(result.getDocid());
			builder.append(" ");
			builder.append(result.getScore());
			builder.append(" ");
			builder.append(result.getTitle());
			builder.append("\n");
			counter++;
		}
		
		
		return builder.toString();
	}
	
	public void write(String outDirectory) {
		try {
			// Writes the string to a file. Here OutputStreamWriter and FileOutputStream are used to specify the path and name of the output file.
			// The file name is generated by replacing spaces in the original query with underscores.
			BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(outDirectory+"/"+query.getOriginalQuery().replace(" ", "_"))));
			writer.write(this.toString());
			writer.close();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
}
